# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy container app to Azure Web App - webappnextjspage

on:
  push:
    branches:
      - main

jobs:

    build-and-push:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-page:latest  # Replace [IMAGE_NAME] with your image name
    deploy:
      permissions:
        contents: none
      runs-on: ubuntu-latest
      needs: build-and-push
      environment:
        name: 'production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'webappnextjspage'
            slot-name: 'production'
            publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
            images: 'index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/nextjs-page:latest'
