name: Deploy on AWS

on:
  workflow_run:
    workflows: ["CI build"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-page:latest
      - name: Stopping container
        run: docker kill prod
      - name: Remove docker container
        run: docker rm -f prod
      - name: Run docker container
        run: docker run -d --name prod -p 3000:8080 ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-page:latest
