name: Build and Push Docker Image

on:
  push:
    branches: [ main ]  # Change "main" to your branch name if needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # You can choose other runners

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-page:latest  # Replace [IMAGE_NAME] with your image name
